theme: minima
google_analytics: G-6TWV9SSCKT
title: Mon portefolio
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
author:
  name: John Smith
  email: "john.smith@foobar.com"
header_pages:
  - about.md
  - portfolio.md
minima:
  social_links:
    - platform: deviantart  # same as SVG filename.
      user_url: "https://www.deviantart.com/john.doe"  # URL of profile page.
      title:  My profile at DeviantArt.com  # Optional. Text displayed on hovering over link.
