theme: minima
google_analytics: G-6TWV9SSCKT
title: Mon portefolio
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
author:
  name: John Smith
  email: "john.smith@foobar.com"
header_pages:
  - about.md
  - portfolio.md
